// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzKrvRII4BHkaczg-hTfCUbePhyE0VwI8',
    appId: '1:472516847364:web:8edf93e2d289f3a3255251',
    messagingSenderId: '472516847364',
    projectId: 'check-in-system-7b9a4',
    authDomain: 'check-in-system-7b9a4.firebaseapp.com',
    storageBucket: 'check-in-system-7b9a4.appspot.com',
    measurementId: 'G-Q5G5B9W5D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLoFDagJzYFC8ele56U2XosK3-9dviBzs',
    appId: '1:472516847364:android:5b6d2159bd75400e255251',
    messagingSenderId: '472516847364',
    projectId: 'check-in-system-7b9a4',
    storageBucket: 'check-in-system-7b9a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlY9EN5opzYa2faTUHgec8aeKELLFqtwQ',
    appId: '1:472516847364:ios:6c7b34b2a34a21da255251',
    messagingSenderId: '472516847364',
    projectId: 'check-in-system-7b9a4',
    storageBucket: 'check-in-system-7b9a4.appspot.com',
    androidClientId: '472516847364-ljb0mlorjgtqqu1r07udg2c8olk0gils.apps.googleusercontent.com',
    iosBundleId: 'com.example.nimuTv',
  );
}
